In [1]:
import keras
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

Using TensorFlow backend.

In [2]:
test_df = pd.read_csv('./data/test.csv')
train_df = pd.read_csv('./data/train.csv')

In [3]:
test_df.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test_df.describe()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,28000.0,...,28000.000000,28000.000000,28000.000000,28000.000000,28000.000000,28000.0,28000.0,28000.0,28000.0,28000.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.164607,0.073214,0.028036,0.011250,0.006536,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.473293,3.616811,1.813602,1.205211,0.807475,0.0,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,254.000000,193.000000,187.000000,119.000000,0.0,0.0,0.0,0.0,0.0

In [5]:
train_df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
standard_scaler = StandardScaler()

In [7]:
Y_train_df = train_df['label']
#Y_train_df = pd.get_dummies(Y_train_df).values
#Y_train_df = Y_train_df.values.reshape(-1, 1)
#Y_train_df = standard_scaler.fit_transform(Y_train_df)
#Y_train_df = keras.utils.np_utils.to_categorical(Y_train_df)
#Y_train_df = Y_train_df.reshape(-1, 10, 1)
Y_train_df.shape

(42000,)

In [8]:
X_train_df = train_df.drop(columns="label")
#X_train_df = standard_scaler.fit_transform(X_train_df)
#X_train_df = keras.utils.np_utils.to_categorical(X_train_df)
X_train_df.shape

(42000, 784)

In [9]:
np.random.seed(7)
# split into 67% for train and 33% for test
X_train, X_valid, y_train, y_valid = train_test_split(X_train_df, Y_train_df, test_size=0.15, random_state=7)

In [40]:
def create_model(train_data):
    # create model
    model = keras.models.Sequential()
    model.add(keras.layers.Dense(800, input_dim=train_data.shape[1], activation='relu'))
    #model.add(keras.layers.Dense(800, activation='relu'))
    model.add(keras.layers.Dense(500, activation='relu'))
    #model.add(keras.layers.Dense(15, activation='relu'))
    model.add(keras.layers.Dense(10))
    model.add(keras.layers.Activation("softmax"))
    # Compile model
    model.compile(optimizer ='sgd', loss = 'sparse_categorical_crossentropy') 
#               metrics =[keras.metrics.mae])
    return model

In [41]:
model = create_model(X_train_df)

In [42]:
history = model.fit(X_train, y_train, validation_data=(X_valid,y_valid), epochs=30, batch_size=1000)

Train on 35700 samples, validate on 6300 samples
Epoch 1/30
35700/35700 [==============================] - 9s 239us/step - loss: 11.3751 - val_loss: 8.8455
Epoch 2/30
35700/35700 [==============================] - 8s 227us/step - loss: 8.3795 - val_loss: 8.4047
Epoch 3/30
35700/35700 [==============================] - 8s 224us/step - loss: 7.8647 - val_loss: 7.2431
Epoch 4/30
35700/35700 [==============================] - 8s 225us/step - loss: 6.9971 - val_loss: 7.0660
Epoch 5/30
35700/35700 [==============================] - 8s 228us/step - loss: 6.8741 - val_loss: 6.9533
Epoch 6/30
35700/35700 [==============================] - 8s 230us/step - loss: 6.0382 - val_loss: 5.6505
Epoch 7/30
35700/35700 [==============================] - 8s 229us/step - loss: 5.3393 - val_loss: 5.5987
Epoch 8/30
35700/35700 [==============================] - 8s 235us/step - loss: 5.2450 - val_loss: 5.4875
Epoch 9/30
35700/35700 [==============================] - 8s 227us/step - loss: 5.1584 - val_loss: 5.4083
Epoch 10/30
35700/35700 [==============================] - 8s 225us/step - loss: 5.1142 - val_loss: 5.3841
Epoch 11/30
35700/35700 [==============================] - 8s 227us/step - loss: 5.0636 - val_loss: 5.3559
Epoch 12/30
35700/35700 [==============================] - 8s 224us/step - loss: 5.0302 - val_loss: 5.3319
Epoch 13/30
35700/35700 [==============================] - 8s 236us/step - loss: 5.0047 - val_loss: 5.3208
Epoch 14/30
35700/35700 [==============================] - 8s 225us/step - loss: 4.3896 - val_loss: 3.8995
Epoch 15/30
35700/35700 [==============================] - 8s 232us/step - loss: 3.6705 - val_loss: 3.8668
Epoch 16/30
35000/35700 [============================>.] - ETA: 0s - loss: 2.5671

KeyboardInterrupt:

In [43]:
answer = model.predict(test_df)

In [44]:
answer = answer.astype(int)

In [45]:
y = np.argmax(answer, axis=-1)
y

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [49]:
frames_aswer = pd.DataFrame({"ImageId": frames_aswer.index.values,
                             "Label": y
                            })

In [50]:
frames_aswer.index += 1
frames_aswer

       ImageId  Label
1            1      2
2            2      0
3            3      9
4            4      0
5            5      3
...        ...    ...
27996    27996      9
27997    27997      9
27998    27998      3
27999    27999      9
28000    28000      2

[28000 rows x 2 columns]

In [51]:
frames_aswer.to_csv('./data/answer.csv', index=True)