In [1]:
import keras
from keras import backend as K
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
img_rows = img_cols = 28
batch_size = 500
num_classes = 10
epochs = 30

Using TensorFlow backend.

In [2]:
test_df = pd.read_csv('./data/test.csv')
train_df = pd.read_csv('./data/train.csv')

In [3]:
test_df.head()

,id,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
test_df.describe()

,id,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
count,5000.000000,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.0,5000.00000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.0,5000.0,5000.000000,5000.0,5000.0,5000.0
mean,2499.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.04780,...,0.191600,0.112600,0.109800,0.078000,0.0,0.0,0.039800,0.0,0.0,0.0
std,1443.520003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.37997,...,6.077753,4.859161,4.766832,4.080104,0.0,0.0,2.814285,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
25%,1249.750000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
50%,2499.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
75%,3749.250000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0
max,4999.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,239.00000,...,255.000000,255.000000,255.000000,255.000000,0.0,0.0,199.000000,0.0,0.0,0.0

In [5]:
train_df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
standard_scaler = StandardScaler()

In [7]:
Y_train_df = train_df['label']
#Y_train_df = pd.get_dummies(Y_train_df)
# Y_train_df = Y_train_df.values.reshape(-1, 1)
# Y_train_df = standard_scaler.fit_transform(Y_train_df)
# Y_train_df = keras.utils.np_utils.to_categorical(Y_train_df)
#Y_train_df = Y_train_df.reshape(-1, 10, 1)
Y_train_df.shape
Y_train_df

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [8]:
X_train_df = train_df.drop(columns="label")
# X_train_df = standard_scaler.fit_transform(X_train_df)
# X_train_df = keras.utils.np_utils.to_categorical(X_train_df)
X_train_df.shape

(60000, 784)

In [9]:
np.random.seed(7)
# split into 67% for train and 33% for test
X_train, X_valid, y_train, y_valid = train_test_split(X_train_df, Y_train_df, test_size=0.15, random_state=7)

In [10]:
X_test = test_df.drop('id', axis = 1)
# X_test = standard_scaler.fit_transform(X_test)
y_test = test_df['id']
# y_test = keras.utils.np_utils.to_categorical(y_test)
y_test

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [11]:
if K.image_data_format() == 'channels_first':
    X_train = X_train.reshape(X_train.shape[0], 1, img_rows, img_cols)
    X_test = X_test.reshape(X_test.shape[0], 1, img_rows, img_cols)
    X_valid = X_valid.reshape(X_valid.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
    X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
    X_valid = X_valid.reshape(X_valid.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

In [12]:
X_train.shape

(51000, 28, 28, 1)

In [13]:
#y_train = np.reshape(y_train.values, ( y_train.shape[0], 1))

In [14]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [15]:
def create_model(train_data, n_classes = 10):
    # create model
    model = keras.models.Sequential()
    model.add(keras.layers.Conv2D(32, kernel_size=(3,3), activation="relu", input_shape=input_shape))
    model.add(keras.layers.Conv2D(64, kernel_size=(3,3), activation="relu"))
    model.add(keras.layers.MaxPooling2D(pool_size=(2, 2)))
    model.add(keras.layers.Dropout(0.25))
    model.add(keras.layers.Flatten())
    model.add(keras.layers.Dense(n_classes, activation="softmax"))
    # Compile model
    model.compile(optimizer ='sgd', loss = 'sparse_categorical_crossentropy')
    return model

In [16]:
model = create_model(X_train_df)

WARNING: Logging before flag parsing goes to stderr.
W1027 13:36:37.458528  3612 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W1027 13:36:37.489511  3612 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W1027 13:36:37.492507  3612 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W1027 13:36:37.537481  3612 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W1027 13:36:37.541479  3612 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W1027 13:36:37.556469  3612 deprecation.py:506] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W1027 13:36:37.643415  3612 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W1027 13:36:37.669398  3612 deprecation_wrapper.py:119] From C:\Users\user\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.

In [17]:
history = model.fit(X_train, y_train, validation_data=(X_valid, y_valid), epochs=epochs, batch_size=batch_size)

W1027 13:36:37.875270  3612 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 51000 samples, validate on 9000 samples
Epoch 1/30
51000/51000 [==============================] - 233s 5ms/step - loss: 0.9624 - mean_absolute_error: 0.0979 - val_loss: 0.3266 - val_mean_absolute_error: 0.0400
Epoch 2/30
51000/51000 [==============================] - 210s 4ms/step - loss: 0.2579 - mean_absolute_error: 0.0300 - val_loss: 0.2091 - val_mean_absolute_error: 0.0236
Epoch 3/30
51000/51000 [==============================] - 249s 5ms/step - loss: 0.1945 - mean_absolute_error: 0.0213 - val_loss: 0.1765 - val_mean_absolute_error: 0.0188
Epoch 4/30
51000/51000 [==============================] - 262s 5ms/step - loss: 0.1730 - mean_absolute_error: 0.0183 - val_loss: 0.1584 - val_mean_absolute_error: 0.0167
Epoch 5/30
51000/51000 [==============================] - 274s 5ms/step - loss: 0.1588 - mean_absolute_error: 0.0165 - val_loss: 0.1508 - val_mean_absolute_error: 0.0155
Epoch 6/30
51000/51000 [==============================] - 282s 6ms/step - loss: 0.1515 - mean_absolute_error: 0.0154 - val_loss: 0.1436 - val_mean_absolute_error: 0.0147
Epoch 7/30
51000/51000 [==============================] - 258s 5ms/step - loss: 0.1445 - mean_absolute_error: 0.0148 - val_loss: 0.1365 - val_mean_absolute_error: 0.0138
Epoch 8/30
51000/51000 [==============================] - 246s 5ms/step - loss: 0.1393 - mean_absolute_error: 0.0141 - val_loss: 0.1330 - val_mean_absolute_error: 0.0133
Epoch 9/30
 6500/51000 [==>...........................] - ETA: 3:10 - loss: 0.1244 - mean_absolute_error: 0.0130

KeyboardInterrupt:

In [18]:
X_test_df = test_df
answer = model.predict(X_test)

In [19]:
answer = answer.astype(int)
answer

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
y = np.argmax(answer, axis=-1)
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
frames_aswer = pd.DataFrame({"ImageId": pd.DataFrame(y).index.values+1,
                             "Label": y
                            })
frames_aswer

      ImageId  Label
0           1      0
1           2      0
2           3      0
3           4      0
4           5      0
...       ...    ...
4995     4996      0
4996     4997      0
4997     4998      0
4998     4999      0
4999     5000      0

[5000 rows x 2 columns]

In [22]:
frames_aswer.to_csv('submission.csv', index=False)